"""Tasks

Revision ID: 629fb894fad2
Revises: 36b92dd708b3
Create Date: 2025-05-06 16:19:42.874028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '629fb894fad2'
down_revision: Union[str, None] = '36b92dd708b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', mysql.MEDIUMTEXT(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('pendiente', 'completada', 'atrasada'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('pendiente', 'completada', 'atrasada'),
               nullable=False)
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
