"""Primera migración

Revision ID: 69e7ec0c4d2b
Revises: 
Create Date: 2025-05-06 10:09:49.291772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69e7ec0c4d2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homeworks', 'status',
               existing_type=mysql.ENUM('pendiente', 'terminada', 'atrasada'),
               type_=sa.Enum('pendiente', 'completada', 'atrasada', name='homeworkstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homeworks', 'status',
               existing_type=sa.Enum('pendiente', 'completada', 'atrasada', name='homeworkstatusenum'),
               type_=mysql.ENUM('pendiente', 'terminada', 'atrasada'),
               existing_nullable=False)
    # ### end Alembic commands ###
