"""Removin description on Tasks

Revision ID: f30b839faf3e
Revises: d4c5142d0423
Create Date: 2025-05-06 11:00:00.478374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f30b839faf3e'
down_revision: Union[str, None] = 'd4c5142d0423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###
